// Generated by gencpp from file user_messages/serialport_decode.msg
// DO NOT EDIT!


#ifndef USER_MESSAGES_MESSAGE_SERIALPORT_DECODE_H
#define USER_MESSAGES_MESSAGE_SERIALPORT_DECODE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace user_messages
{
template <class ContainerAllocator>
struct serialport_decode_
{
  typedef serialport_decode_<ContainerAllocator> Type;

  serialport_decode_()
    : buf()
    , cnt(0)  {
    }
  serialport_decode_(const ContainerAllocator& _alloc)
    : buf(_alloc)
    , cnt(0)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _buf_type;
  _buf_type buf;

   typedef uint16_t _cnt_type;
  _cnt_type cnt;





  typedef boost::shared_ptr< ::user_messages::serialport_decode_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::user_messages::serialport_decode_<ContainerAllocator> const> ConstPtr;

}; // struct serialport_decode_

typedef ::user_messages::serialport_decode_<std::allocator<void> > serialport_decode;

typedef boost::shared_ptr< ::user_messages::serialport_decode > serialport_decodePtr;
typedef boost::shared_ptr< ::user_messages::serialport_decode const> serialport_decodeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::user_messages::serialport_decode_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::user_messages::serialport_decode_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::user_messages::serialport_decode_<ContainerAllocator1> & lhs, const ::user_messages::serialport_decode_<ContainerAllocator2> & rhs)
{
  return lhs.buf == rhs.buf &&
    lhs.cnt == rhs.cnt;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::user_messages::serialport_decode_<ContainerAllocator1> & lhs, const ::user_messages::serialport_decode_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace user_messages

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::user_messages::serialport_decode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::user_messages::serialport_decode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::user_messages::serialport_decode_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::user_messages::serialport_decode_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::user_messages::serialport_decode_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::user_messages::serialport_decode_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::user_messages::serialport_decode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b64998cbe9ab1eb940716392cc08fe66";
  }

  static const char* value(const ::user_messages::serialport_decode_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb64998cbe9ab1eb9ULL;
  static const uint64_t static_value2 = 0x40716392cc08fe66ULL;
};

template<class ContainerAllocator>
struct DataType< ::user_messages::serialport_decode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "user_messages/serialport_decode";
  }

  static const char* value(const ::user_messages::serialport_decode_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::user_messages::serialport_decode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8[] buf\n"
"uint16 cnt\n"
;
  }

  static const char* value(const ::user_messages::serialport_decode_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::user_messages::serialport_decode_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.buf);
      stream.next(m.cnt);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct serialport_decode_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::user_messages::serialport_decode_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::user_messages::serialport_decode_<ContainerAllocator>& v)
  {
    s << indent << "buf[]" << std::endl;
    for (size_t i = 0; i < v.buf.size(); ++i)
    {
      s << indent << "  buf[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.buf[i]);
    }
    s << indent << "cnt: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.cnt);
  }
};

} // namespace message_operations
} // namespace ros

#endif // USER_MESSAGES_MESSAGE_SERIALPORT_DECODE_H
