set(_CATKIN_CURRENT_PACKAGE "combined_pkg")
set(combined_pkg_VERSION "0.0.0")
set(combined_pkg_MAINTAINER "ubuntu <ubuntu@todo.todo>")
set(combined_pkg_PACKAGE_FORMAT "2")
set(combined_pkg_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(combined_pkg_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(combined_pkg_BUILDTOOL_DEPENDS "catkin")
set(combined_pkg_BUILDTOOL_EXPORT_DEPENDS )
set(combined_pkg_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(combined_pkg_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(combined_pkg_TEST_DEPENDS )
set(combined_pkg_DOC_DEPENDS )
set(combined_pkg_URL_WEBSITE "")
set(combined_pkg_URL_BUGTRACKER "")
set(combined_pkg_URL_REPOSITORY "")
set(combined_pkg_DEPRECATED "")