set(_CATKIN_CURRENT_PACKAGE "send_pos_to_px4_node")
set(send_pos_to_px4_node_VERSION "0.0.0")
set(send_pos_to_px4_node_MAINTAINER "shili <shili@todo.todo>")
set(send_pos_to_px4_node_PACKAGE_FORMAT "2")
set(send_pos_to_px4_node_BUILD_DEPENDS "geometry_msgs" "mavros_msgs" "roscpp" "rospy" "std_msgs")
set(send_pos_to_px4_node_BUILD_EXPORT_DEPENDS "geometry_msgs" "mavros_msgs" "roscpp" "rospy" "std_msgs")
set(send_pos_to_px4_node_BUILDTOOL_DEPENDS "catkin")
set(send_pos_to_px4_node_BUILDTOOL_EXPORT_DEPENDS )
set(send_pos_to_px4_node_EXEC_DEPENDS "geometry_msgs" "mavros_msgs" "roscpp" "rospy" "std_msgs")
set(send_pos_to_px4_node_RUN_DEPENDS "geometry_msgs" "mavros_msgs" "roscpp" "rospy" "std_msgs")
set(send_pos_to_px4_node_TEST_DEPENDS )
set(send_pos_to_px4_node_DOC_DEPENDS )
set(send_pos_to_px4_node_URL_WEBSITE "")
set(send_pos_to_px4_node_URL_BUGTRACKER "")
set(send_pos_to_px4_node_URL_REPOSITORY "")
set(send_pos_to_px4_node_DEPRECATED "")