// Generated by gencpp from file lanya_pkg/xc_wz_data.msg
// DO NOT EDIT!


#ifndef LANYA_PKG_MESSAGE_XC_WZ_DATA_H
#define LANYA_PKG_MESSAGE_XC_WZ_DATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lanya_pkg
{
template <class ContainerAllocator>
struct xc_wz_data_
{
  typedef xc_wz_data_<ContainerAllocator> Type;

  xc_wz_data_()
    : xc_x(0.0)
    , xc_y(0.0)  {
    }
  xc_wz_data_(const ContainerAllocator& _alloc)
    : xc_x(0.0)
    , xc_y(0.0)  {
  (void)_alloc;
    }



   typedef float _xc_x_type;
  _xc_x_type xc_x;

   typedef float _xc_y_type;
  _xc_y_type xc_y;





  typedef boost::shared_ptr< ::lanya_pkg::xc_wz_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lanya_pkg::xc_wz_data_<ContainerAllocator> const> ConstPtr;

}; // struct xc_wz_data_

typedef ::lanya_pkg::xc_wz_data_<std::allocator<void> > xc_wz_data;

typedef boost::shared_ptr< ::lanya_pkg::xc_wz_data > xc_wz_dataPtr;
typedef boost::shared_ptr< ::lanya_pkg::xc_wz_data const> xc_wz_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lanya_pkg::xc_wz_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lanya_pkg::xc_wz_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lanya_pkg::xc_wz_data_<ContainerAllocator1> & lhs, const ::lanya_pkg::xc_wz_data_<ContainerAllocator2> & rhs)
{
  return lhs.xc_x == rhs.xc_x &&
    lhs.xc_y == rhs.xc_y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lanya_pkg::xc_wz_data_<ContainerAllocator1> & lhs, const ::lanya_pkg::xc_wz_data_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lanya_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::lanya_pkg::xc_wz_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lanya_pkg::xc_wz_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lanya_pkg::xc_wz_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lanya_pkg::xc_wz_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lanya_pkg::xc_wz_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lanya_pkg::xc_wz_data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lanya_pkg::xc_wz_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0af5983c67c5a0659bc718afae52c5bd";
  }

  static const char* value(const ::lanya_pkg::xc_wz_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0af5983c67c5a065ULL;
  static const uint64_t static_value2 = 0x9bc718afae52c5bdULL;
};

template<class ContainerAllocator>
struct DataType< ::lanya_pkg::xc_wz_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lanya_pkg/xc_wz_data";
  }

  static const char* value(const ::lanya_pkg::xc_wz_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lanya_pkg::xc_wz_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 xc_x\n"
"float32 xc_y\n"
;
  }

  static const char* value(const ::lanya_pkg::xc_wz_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lanya_pkg::xc_wz_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.xc_x);
      stream.next(m.xc_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct xc_wz_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lanya_pkg::xc_wz_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lanya_pkg::xc_wz_data_<ContainerAllocator>& v)
  {
    s << indent << "xc_x: ";
    Printer<float>::stream(s, indent + "  ", v.xc_x);
    s << indent << "xc_y: ";
    Printer<float>::stream(s, indent + "  ", v.xc_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LANYA_PKG_MESSAGE_XC_WZ_DATA_H
