// Generated by gencpp from file test/all_position.msg
// DO NOT EDIT!


#ifndef TEST_MESSAGE_ALL_POSITION_H
#define TEST_MESSAGE_ALL_POSITION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test
{
template <class ContainerAllocator>
struct all_position_
{
  typedef all_position_<ContainerAllocator> Type;

  all_position_()
    : id(0)
    , x1(0.0)
    , y1(0.0)
    , x2(0.0)
    , y2(0.0)
    , angle(0.0)  {
    }
  all_position_(const ContainerAllocator& _alloc)
    : id(0)
    , x1(0.0)
    , y1(0.0)
    , x2(0.0)
    , y2(0.0)
    , angle(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef double _x1_type;
  _x1_type x1;

   typedef double _y1_type;
  _y1_type y1;

   typedef double _x2_type;
  _x2_type x2;

   typedef double _y2_type;
  _y2_type y2;

   typedef double _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::test::all_position_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test::all_position_<ContainerAllocator> const> ConstPtr;

}; // struct all_position_

typedef ::test::all_position_<std::allocator<void> > all_position;

typedef boost::shared_ptr< ::test::all_position > all_positionPtr;
typedef boost::shared_ptr< ::test::all_position const> all_positionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test::all_position_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test::all_position_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::test::all_position_<ContainerAllocator1> & lhs, const ::test::all_position_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.x1 == rhs.x1 &&
    lhs.y1 == rhs.y1 &&
    lhs.x2 == rhs.x2 &&
    lhs.y2 == rhs.y2 &&
    lhs.angle == rhs.angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::test::all_position_<ContainerAllocator1> & lhs, const ::test::all_position_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace test

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::test::all_position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test::all_position_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test::all_position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test::all_position_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test::all_position_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test::all_position_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test::all_position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b638085ef920f701afd51e311a64a083";
  }

  static const char* value(const ::test::all_position_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb638085ef920f701ULL;
  static const uint64_t static_value2 = 0xafd51e311a64a083ULL;
};

template<class ContainerAllocator>
struct DataType< ::test::all_position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test/all_position";
  }

  static const char* value(const ::test::all_position_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test::all_position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 id\n"
"float64 x1\n"
"float64 y1\n"
"float64 x2\n"
"float64 y2\n"
"\n"
"float64 angle\n"
"\n"
;
  }

  static const char* value(const ::test::all_position_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test::all_position_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.x1);
      stream.next(m.y1);
      stream.next(m.x2);
      stream.next(m.y2);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct all_position_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test::all_position_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test::all_position_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "x1: ";
    Printer<double>::stream(s, indent + "  ", v.x1);
    s << indent << "y1: ";
    Printer<double>::stream(s, indent + "  ", v.y1);
    s << indent << "x2: ";
    Printer<double>::stream(s, indent + "  ", v.x2);
    s << indent << "y2: ";
    Printer<double>::stream(s, indent + "  ", v.y2);
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_MESSAGE_ALL_POSITION_H
