// Generated by gencpp from file test/arm_state.msg
// DO NOT EDIT!


#ifndef TEST_MESSAGE_ARM_STATE_H
#define TEST_MESSAGE_ARM_STATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test
{
template <class ContainerAllocator>
struct arm_state_
{
  typedef arm_state_<ContainerAllocator> Type;

  arm_state_()
    : chess_aim_x(0.0)
    , chess_aim_y(0.0)  {
    }
  arm_state_(const ContainerAllocator& _alloc)
    : chess_aim_x(0.0)
    , chess_aim_y(0.0)  {
  (void)_alloc;
    }



   typedef float _chess_aim_x_type;
  _chess_aim_x_type chess_aim_x;

   typedef float _chess_aim_y_type;
  _chess_aim_y_type chess_aim_y;





  typedef boost::shared_ptr< ::test::arm_state_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test::arm_state_<ContainerAllocator> const> ConstPtr;

}; // struct arm_state_

typedef ::test::arm_state_<std::allocator<void> > arm_state;

typedef boost::shared_ptr< ::test::arm_state > arm_statePtr;
typedef boost::shared_ptr< ::test::arm_state const> arm_stateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test::arm_state_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test::arm_state_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::test::arm_state_<ContainerAllocator1> & lhs, const ::test::arm_state_<ContainerAllocator2> & rhs)
{
  return lhs.chess_aim_x == rhs.chess_aim_x &&
    lhs.chess_aim_y == rhs.chess_aim_y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::test::arm_state_<ContainerAllocator1> & lhs, const ::test::arm_state_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace test

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::test::arm_state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test::arm_state_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test::arm_state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test::arm_state_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test::arm_state_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test::arm_state_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test::arm_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "021ae4e1499fe0af22a25b5797cdfc12";
  }

  static const char* value(const ::test::arm_state_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x021ae4e1499fe0afULL;
  static const uint64_t static_value2 = 0x22a25b5797cdfc12ULL;
};

template<class ContainerAllocator>
struct DataType< ::test::arm_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test/arm_state";
  }

  static const char* value(const ::test::arm_state_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test::arm_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 chess_aim_x     # 棋子目的位置x\n"
"float32 chess_aim_y     # 棋子目的位置y\n"
"\n"
"\n"
"\n"
"\n"
;
  }

  static const char* value(const ::test::arm_state_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test::arm_state_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.chess_aim_x);
      stream.next(m.chess_aim_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct arm_state_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test::arm_state_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test::arm_state_<ContainerAllocator>& v)
  {
    s << indent << "chess_aim_x: ";
    Printer<float>::stream(s, indent + "  ", v.chess_aim_x);
    s << indent << "chess_aim_y: ";
    Printer<float>::stream(s, indent + "  ", v.chess_aim_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_MESSAGE_ARM_STATE_H
