// Generated by gencpp from file test/next_piece.msg
// DO NOT EDIT!


#ifndef TEST_MESSAGE_NEXT_PIECE_H
#define TEST_MESSAGE_NEXT_PIECE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test
{
template <class ContainerAllocator>
struct next_piece_
{
  typedef next_piece_<ContainerAllocator> Type;

  next_piece_()
    : next(0)  {
    }
  next_piece_(const ContainerAllocator& _alloc)
    : next(0)  {
  (void)_alloc;
    }



   typedef int32_t _next_type;
  _next_type next;





  typedef boost::shared_ptr< ::test::next_piece_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test::next_piece_<ContainerAllocator> const> ConstPtr;

}; // struct next_piece_

typedef ::test::next_piece_<std::allocator<void> > next_piece;

typedef boost::shared_ptr< ::test::next_piece > next_piecePtr;
typedef boost::shared_ptr< ::test::next_piece const> next_pieceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test::next_piece_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test::next_piece_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::test::next_piece_<ContainerAllocator1> & lhs, const ::test::next_piece_<ContainerAllocator2> & rhs)
{
  return lhs.next == rhs.next;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::test::next_piece_<ContainerAllocator1> & lhs, const ::test::next_piece_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace test

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::test::next_piece_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test::next_piece_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test::next_piece_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test::next_piece_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test::next_piece_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test::next_piece_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test::next_piece_<ContainerAllocator> >
{
  static const char* value()
  {
    return "89e3abdd267d92f91c4ae5f000c4dde5";
  }

  static const char* value(const ::test::next_piece_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x89e3abdd267d92f9ULL;
  static const uint64_t static_value2 = 0x1c4ae5f000c4dde5ULL;
};

template<class ContainerAllocator>
struct DataType< ::test::next_piece_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test/next_piece";
  }

  static const char* value(const ::test::next_piece_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test::next_piece_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 next\n"
;
  }

  static const char* value(const ::test::next_piece_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test::next_piece_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.next);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct next_piece_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test::next_piece_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test::next_piece_<ContainerAllocator>& v)
  {
    s << indent << "next: ";
    Printer<int32_t>::stream(s, indent + "  ", v.next);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_MESSAGE_NEXT_PIECE_H
