set(_CATKIN_CURRENT_PACKAGE "first_fly_node")
set(first_fly_node_VERSION "0.0.0")
set(first_fly_node_MAINTAINER "shili <shili@todo.todo>")
set(first_fly_node_PACKAGE_FORMAT "2")
set(first_fly_node_BUILD_DEPENDS "geometry_msgs" "mavros_msgs" "roscpp" "rospy" "std_msgs")
set(first_fly_node_BUILD_EXPORT_DEPENDS "geometry_msgs" "mavros_msgs" "roscpp" "rospy" "std_msgs")
set(first_fly_node_BUILDTOOL_DEPENDS "catkin")
set(first_fly_node_BUILDTOOL_EXPORT_DEPENDS )
set(first_fly_node_EXEC_DEPENDS "geometry_msgs" "mavros_msgs" "roscpp" "rospy" "std_msgs")
set(first_fly_node_RUN_DEPENDS "geometry_msgs" "mavros_msgs" "roscpp" "rospy" "std_msgs")
set(first_fly_node_TEST_DEPENDS )
set(first_fly_node_DOC_DEPENDS )
set(first_fly_node_URL_WEBSITE "")
set(first_fly_node_URL_BUGTRACKER "")
set(first_fly_node_URL_REPOSITORY "")
set(first_fly_node_DEPRECATED "")