// Generated by gencpp from file test/avoidant_date.msg
// DO NOT EDIT!


#ifndef TEST_MESSAGE_AVOIDANT_DATE_H
#define TEST_MESSAGE_AVOIDANT_DATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test
{
template <class ContainerAllocator>
struct avoidant_date_
{
  typedef avoidant_date_<ContainerAllocator> Type;

  avoidant_date_()
    : x(0.0)
    , y(0.0)  {
    }
  avoidant_date_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::test::avoidant_date_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test::avoidant_date_<ContainerAllocator> const> ConstPtr;

}; // struct avoidant_date_

typedef ::test::avoidant_date_<std::allocator<void> > avoidant_date;

typedef boost::shared_ptr< ::test::avoidant_date > avoidant_datePtr;
typedef boost::shared_ptr< ::test::avoidant_date const> avoidant_dateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test::avoidant_date_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test::avoidant_date_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::test::avoidant_date_<ContainerAllocator1> & lhs, const ::test::avoidant_date_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::test::avoidant_date_<ContainerAllocator1> & lhs, const ::test::avoidant_date_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace test

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::test::avoidant_date_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test::avoidant_date_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test::avoidant_date_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test::avoidant_date_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test::avoidant_date_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test::avoidant_date_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test::avoidant_date_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ff8d7d66dd3e4b731ef14a45d38888b6";
  }

  static const char* value(const ::test::avoidant_date_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xff8d7d66dd3e4b73ULL;
  static const uint64_t static_value2 = 0x1ef14a45d38888b6ULL;
};

template<class ContainerAllocator>
struct DataType< ::test::avoidant_date_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test/avoidant_date";
  }

  static const char* value(const ::test::avoidant_date_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test::avoidant_date_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32  x\n"
"float32  y\n"
"\n"
"\n"
"\n"
"\n"
;
  }

  static const char* value(const ::test::avoidant_date_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test::avoidant_date_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct avoidant_date_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test::avoidant_date_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test::avoidant_date_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_MESSAGE_AVOIDANT_DATE_H
